ignore:
  - "engine/testing_*.go"
  - "engine/game.go"
  - "engine/idiom.go"
  - "engine/vec2d.go"
  - "engine/logger.go"
  - "engine/math.go"
  - "engine/sdl.go"
  - "engine/spatial_hash_table_to_string.go"
