ignore:
  - "engine/testing_*.go"
  - "engine/game.go"
  - "engine/game_screen.go"
  - "engine/idiom.go"
  - "engine/vec2d.go"
  - "engine/logger.go"
  - "engine/math.go"
  - "engine/sdl.go"
  - "engine/GENERATED_entity_components_get_methods.go"
